### PR TITLE
FIX: Setenv ignored in command list user & group

### PR DESCRIPTION
**Pull request by autarchprinceps**

### CODE REVIEW

**Comment by tas50** [comment]
@autarchprinceps Thanks for the contribution. Before this can get merged we'll need the commit to be signed off for the DCO. You can read me about the process here: https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

Additionally can you remove the version bump. We have tooling that handles that bump along with changelog generation.

**Comment by autarchprinceps** [comment]
@tas50 This should do it, right? Also FYI the travis build failed, but not because of me and only on one machine type and in one run only and I do use my change through the fork and have therefore tested it.

**Comment by autarchprinceps** [comment]
I changed what you wanted. Is there some other issue, or why are you not merging it?

**Comment by tas50** [comment]
Nothing in particular was holding this up, just the pile of things to do throughout the cookbook ecosystem. Thanks for getting this fixed and then updated.

**Comment by autarchprinceps** [comment]
No problem, just though you might have just forgotten about it. Thanks for merging it.

**Pull request merged**
