### PR TITLE
Make sure the package is installed at compile time versus waitin until execution phase.

### PR DESCRIPTION
**Pull request by iennae**
### Description

Make sure the package is installed at compile time versus waiting until execution phase.

### Issues Resolved

Issue #103 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by pantocrator27** [comment]
ping

**Comment by jblaine** [comment]
Curious. Why? There's no motivation mentioned. This change presupposes incorrectly that the host in question has been properly configured (somehow?) before compile-time to be able to install packages from the vendor's upstream location. This most definitely is not the case in our environment where we have to configure a system-wide and/or packaging-tool-specific HTTP proxy, let alone properly subscribe our RH hosts to Red Hat Subscription Manager.

**Comment by iennae** [comment]
@jblaine the motivation is the linked issue. Right now the behavior of the resource is to try to https://github.com/chef-cookbooks/sudo/blob/e9114f63ba144072fc4407d83ab7bbd162f898d0/providers/default.rb#L122 configure the sudoers but if the package isn't ready this causes an error. The right behavior may be to change up how the default resource works currently so it doesn't use run_action at all. @tas50 has been refactoring this cookbook so this fix may not be needed (Which is why this hasn't been merged in yet.)

**Comment by tas50** [comment]
I switched this install to only happen when running on docker and to install at compile time. It fixes the problem users reported w/o breaking other users due to package systems not being ready.

**Pull request closed without merging**
