### PR TITLE
Add support for env_keep in the sudoer LWRP

### PR DESCRIPTION
**Pull request by clewis**
env_keep_add will add things to the env_keep.
env_keep_subtract will remove things from the env_keep.

### CODE REVIEW

**Comment by miketheman** [comment]
@cwebberOps When might this cookbook be released to contain this feature?

**Comment by acqant** [comment]
@cwebberOps 

+1 on a 2.7.2? release?

**Comment by miketheman** [comment]
@opscode-cookbooks/owners What can we do to help get this released?
https://github.com/opscode-cookbooks/sudo/compare/v2.7.1...master?w=1

**Comment by someara** [comment]
2.7.2 has been released

**Pull request merged**
