### PR TITLE
Remove sysadmin from default groups

### PR DESCRIPTION
**Pull request by barrowkwan**
### Description
sysadmins not necessary exist.  #97 supposed to take care of this.

### CODE REVIEW

**Comment by tas50** [comment]
Merging under the obvious fix policy. Thanks for noticing this one

**Comment by TD-4242** [comment]
```
log 'message' do
  message 'sysadmin group is deprecated and will be removed'
  level :warn
end
```

**Comment by koertkuipers** [comment]
wow. this was NOT a small change. to put this in a minor bump (version 3.5.0 -> 3.5.1) is very dangerous.
we do testing but we did not catch this one. i ran it on one machine and got locked out as sysadmin. luckily i noticed it and immediately revered back to sudo 3.5.0 before running chef on other machines.

**Comment by barrowkwan** [comment]
I don't know why you will need to revere back to 3.5.0.  All you need is to define  authorization['sudo']['groups'] = ['sysadmin'] in your node or role or environment, no?

**Comment by koertkuipers** [comment]
Yeah but telling all the people in our company that manage
environments/roles to make that change or be locked out when upgrading a
hotfix release of sudo cookbook is not a great process. Easier to just tell
them not to upgrade this cookbook for now (which is a pretty standard
process).

**Pull request merged**
