### PR TITLE
Add NOEXEC support

### PR DESCRIPTION
**Pull request by kemra102**
### Description

This pull request adds support for the NOEXEC option which stops commands that allow shelling out from doing so.

### Issues Resolved

N/A

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by kemra102** [comment]
The tests aren't truly failing it's either timing out trying to install busser-bats or failing to sudo as the kitchen user.

The cookbook tests themselves never actually run.

**Comment by tas50** [comment]
@kemra102 I've replaced the flakey bats tests with inspec so the tests should be good to go now.  Can you rebase this against that release and I'll get it merged in.

**Comment by kemra102** [comment]
@tas50 Done & updated tests for this feature

**Comment by tas50** [comment]
Thanks for the quick response @kemra102

**Pull request merged**
